<template>
  <main class="personal-content">
    <section class="personal-section intro-section"><h2>Hong Kong Personal Banking Services</h2><p>Hong Kong personal bank accounts can support overseas study, property purchase, investment, immigration and cross-border living expenses. We help match applicants with suitable banks based on identity, purpose and source of funds. Final requirements and approval remain subject to the bank's review.</p></section>
    <section class="personal-section"><h2>Common Uses</h2><div class="feature-grid"><article v-for="item in features" :key="item.title"><strong>{{ item.title }}</strong><p>{{ item.text }}</p></article></div></section>
    <section class="personal-section requirements-section"><h2>Common Documents</h2><div class="requirement-grid"><div v-for="item in requirements" :key="item" class="requirement">{{ item }}</div></div><p class="note">Document, address, balance and compliance requirements vary by bank. The latest requirements of the selected bank apply.</p></section>
    <section class="personal-section"><h2>Application Process</h2><div class="steps"><div v-for="(item, index) in steps" :key="item.title" class="step"><span>{{ String(index + 1).padStart(2, '0') }}</span><strong>{{ item.title }}</strong><p>{{ item.text }}</p></div></div></section>
    <section class="personal-section maintenance-section"><h2>Account Maintenance</h2><ul><li v-for="item in maintenance" :key="item">{{ item }}</li></ul></section>
    <section class="personal-section bank-section"><h2>Hong Kong Banks Available for Personal Account Consultation</h2><div class="bank-grid"><div v-for="bank in banks" :key="bank.name" class="bank-card"><img :src="bank.img" :alt="bank.name" loading="lazy"><span>{{ bank.name }}</span></div></div></section>
    <section class="personal-section faq-section"><h2>Frequently Asked Questions</h2><details v-for="item in faqs" :key="item.q"><summary>{{ item.q }}</summary><p>{{ item.a }}</p></details></section>
  </main>
</template>
<script setup>
import '@/css_en/bank_personal/hk/Personal_content.css'
const image = (name) => new URL(`../../../assets/img/bank/hk/${name}`, import.meta.url).href
const features = [{ title: 'Multi-currency management', text: 'Manage HKD, RMB, USD and other currencies subject to the bank and account type.' }, { title: 'Overseas payments', text: 'Useful for tuition, property, insurance and everyday cross-border spending.' }, { title: 'Cross-border banking', text: 'Use online banking, cards and remittance services according to account features.' }, { title: 'Global wealth planning', text: 'Build a compliant banking foundation for personal wealth management.' }]
const requirements = ['Valid Mainland Chinese ID card', 'Hong Kong and Macau travel permit or passport', 'Entry record or landing slip', 'Proof of address or correspondence details', 'Tax residency self-certification', 'Source of funds and account purpose']
const steps = [{ title: 'Consultation', text: 'Review identity, purpose, source of funds and bank preferences.' }, { title: 'Document review', text: 'Prepare and supplement documents required by the selected bank.' }, { title: 'Appointment', text: 'Book a branch appointment and attend identity verification in Hong Kong.' }, { title: 'Compliance review', text: 'The bank completes due diligence and account approval.' }, { title: 'Activation', text: 'Receive account materials and activate online banking and cards.' }]
const maintenance = ['Keep reasonable and compliant account activity.', 'Respond promptly to bank requests for information or transaction reviews.', 'Keep evidence of source of funds and transaction purpose.', 'Maintain valid contact details and observe balance and fee requirements.']
const banks = [['CCB (Asia)','construction.png'], ['Bank of China (Hong Kong)','china.jpg'], ['Bank of Communications','communications.jpg'], ['CMB Wing Lung Bank','merchants_wing_lung.jpg'], ['China CITIC Bank','china_citic.jpg'], ['HSBC','HSBC.jpg'], ['Chong Hing Bank','chong_xing.jpg'], ['DBS Bank','DBS.jpg'], ['Hang Seng Bank','hang_seng.jpg'], ['Nanyang Commercial Bank','NCB.jpg'], ['Bank of East Asia','east_asia.jpg'], ['Dah Sing Bank','dah_sing.jpg'], ['OCBC Bank (Hong Kong)','OCBC.jpg'], ['Citibank Hong Kong','citibank.jpg'], ['Standard Chartered Hong Kong','Standard_Chartered.jpg'], ['ICBC (Asia)','ICBC.jpg'], ['Shanghai Commercial Bank','ShangHai.png']].map(([name, file]) => ({ name, img: image(file) }))
const faqs = [{ q: 'Can Mainland residents apply for a Hong Kong personal account?', a: 'Some Hong Kong banks accept eligible Mainland residents. Acceptance and documents depend on the bank and customer profile.' }, { q: 'Is an in-person visit required?', a: 'Most traditional banks require identity verification and an interview at a Hong Kong branch. Remote options, if any, are subject to the bank.' }, { q: 'How long does opening take?', a: 'Appointment availability and compliance review times vary. No fixed approval time can be guaranteed.' }, { q: 'What happens if the account is inactive?', a: 'The bank may request updates or conduct a risk review. Keep the account compliant and respond to notices promptly.' }]
</script>
