// Each entry describes personal services only. Unverified eligibility is explicit.
const profile = (zh, en, documentsZh, documentsEn, channelZh, channelEn, source, status = 'personal') => ({
  zh: { eligibility: zh, documents: documentsZh, channel: channelZh },
  en: { eligibility: en, documents: documentsEn, channel: channelEn },
  source, status, checkedAt: '2026-10-04'
})
export const personalBankProfiles = {
  hk: {
    constructions: profile('建行亚洲 e-Account 提供内地访港人士申请渠道，申请时须在香港，并满足该渠道的年龄、证件及税务身份条件。', 'CCB Asia e-Account has a channel for Mainland visitors who apply while in Hong Kong and meet its age, identification and tax-status criteria.', ['有效内地身份证', '有效港澳通行证', '入出境记录；其他资料按申请渠道补充'], ['Valid Mainland identity card', 'Valid Exit/Entry Permit', 'Entry/exit record; additional channel-specific documents'], '使用银行 e-Account 渠道核验身份；不等于人在内地远程开户。', 'Apply through the bank’s e-Account verification channel; this is not an application from Mainland China.', 'https://www.asia.ccb.com/hongkong/personal/accounts/eaccount.html'),
    boc: profile('中银香港个人开户须区分手机申请、网点办理及跨境见证渠道；见证服务有客户资格及指定网点要求。', 'BOCHK offers different mobile, branch and cross-border witnessing channels. Witnessing is subject to customer eligibility and designated locations.', ['所选渠道接受的有效身份证明', '旅行及入境资料（如适用）', '所选产品及税务身份要求的补充资料'], ['Identification accepted by the selected channel', 'Travel and entry documents where applicable', 'Additional product and tax-status documents'], '先确认申请渠道及资格，再按银行安排进行身份核验。', 'Confirm channel eligibility before completing the bank’s identity verification.', 'https://www.bochk.com/m/sc/crossborder/personal/financialservicehk/account.html'),
    hsbc: profile('汇丰香港个人开户文件按香港居民与非香港居民身份区分，存款与投资服务的资料要求不同。', 'HSBC Hong Kong distinguishes resident and non-resident documentation, with different requirements for deposit and investment services.', ['香港身份证或银行接受的有效旅行证件', '非香港居民的国籍及身份证明资料', '地址及所申请服务要求的补充证明'], ['HKID or accepted valid travel document', 'Nationality and identification details for non-residents', 'Address and service-specific supporting evidence'], '按个人开户文件说明选择适用的申请方式。', 'Choose an eligible channel using the bank’s personal account documentation guide.', 'https://www.hsbc.com.hk/content/dam/hsbc/hk/docs/accounts/applyaccount-note-en.pdf'),
    communications: profile('交通银行（香港）有限公司的个人开户清单要求有效身份文件；非香港永久居民还需提供国籍证明。', 'Bank of Communications (Hong Kong) Limited requires valid identification and nationality evidence for non-permanent Hong Kong residents.', ['有效身份证明文件正本', '国籍证明，如护照（适用人士）', '投资服务所需的近期住址证明（如适用）'], ['Original valid identification', 'Nationality evidence such as a passport where applicable', 'Recent address proof for investment services where applicable'], '向银行确认个人账户申请安排并携带原件核验。', 'Confirm personal account arrangements with the bank and present original documents.', 'https://www.bankcomm.com.hk/hk/uploadhk/infos/201801/29/2600206/20211223181157_Checklist_individual_202201_EN.pdf'),
    'cmb-winglung': profile('招商永隆的个人存款文件清单列有内地居民身份证与有效旅行证件组合，银行会了解职业、收入、开户目的及预期交易。', 'CMB Wing Lung lists Mainland ID with a valid travel document and requests occupation, income, account purpose and expected transaction information.', ['内地身份证及有效旅行证件，或其他认可身份证明', '职业、收入及资金来源资料', '税务居民身份；投资服务住址证明（如适用）'], ['Mainland ID and valid travel document, or other accepted ID', 'Occupation, income and source-of-funds information', 'Tax residency; investment address proof where applicable'], '准备个人存款资料并按银行安排提交申请。', 'Prepare personal deposit documentation and follow the bank’s submission arrangements.', 'https://ac.cmbwinglungbank.com/wlb_corporate/files/en/upload/personal/deposits/identity-document-list01.pdf'),
    citic: profile('中信银行（国际）inMotion 内地居民开户渠道须核对有效证件、在港申请及新客户条件，线上申请不代表所有柜台服务均已启用。', 'CNCBI inMotion Mainland onboarding has document, Hong Kong location and new-customer criteria. Digital onboarding does not automatically activate every branch service.', ['有效内地身份证', '有效港澳通行证及签注', '入出境记录及申请要求的补充信息'], ['Valid Mainland identity card', 'Valid Exit/Entry Permit and endorsement', 'Entry/exit record and additional application information'], '通过 inMotion 申请；需柜台核验的服务按银行安排另行办理。', 'Apply through inMotion; complete branch verification separately for services that require it.', 'https://www.cncbinternational.com/personal/e-banking/inmotion/en/aboutus/index.html'),
    dbs: profile('星展香港 DBS Account 的内地居民手机申请渠道面向符合条件的成年新客户，申请时须在香港，并有美国人士限制。', 'DBS Hong Kong’s Mainland mobile channel is for eligible adult new customers applying in Hong Kong, with restrictions concerning U.S. persons.', ['有效内地身份证', '银行指定的旅行及入境资料', '个人及税务居民信息'], ['Valid Mainland identity card', 'Travel and entry records specified by the bank', 'Personal and tax-residency information'], '使用 DBS digibank HK 的适用开户渠道完成核验。', 'Complete verification through the eligible DBS digibank HK channel.', 'https://www.dbs.com.hk/personal/deposits/accounts/dbs-account'),
    hangseng: profile('恒生手机开户要求申请人在香港，并按香港身份证或内地居民证件渠道核验；网点及其他身份申请的资料另有清单。', 'Hang Seng mobile onboarding requires applicants to be in Hong Kong and uses separate HKID and Mainland document channels. Other applicants have separate branch requirements.', ['适用身份证明文件', '内地申请人的港澳通行证及入境记录', '投资账户住址证明（如适用）'], ['Applicable identification', 'Exit/Entry Permit and entry record for Mainland applicants', 'Address proof for investment accounts where applicable'], '选择符合本人身份的手机或网点申请渠道。', 'Choose the mobile or branch channel matching your identity.', 'https://www.hangseng.com/content/dam/wpb/hase/en_hk/personal/banking-services/pdf/account_opening_document_checklist.pdf'),
    ncb: profile('南洋商业银行个人及联名账户清单接受多类身份证件，包括内地身份证配合有效港澳通行证；须提供开户目的等尽职调查信息。', 'NCB’s personal and joint-account checklist includes Mainland ID with a valid Exit/Entry Permit and requests account-purpose and due-diligence information.', ['银行认可的身份证件正本', '职业、收入、开户目的及预期交易资料', '税务居民信息；投资服务住址证明（如适用）'], ['Original accepted identification', 'Occupation, income, purpose and expected transactions', 'Tax residency; investment address proof where applicable'], '依个人及联名账户清单向银行提交资料。', 'Submit documents under the personal/joint-account checklist.', 'https://www.ncb.com.hk/nanyang_bank/resource/req_open_per_join_acc_eng.pdf'),
    dahsing: profile('大新网点个人存款申请与 e-Express 线上申请的资格不同；e-Express 有香港永久居民身份证及现有账户限制。', 'Dah Sing branch deposit applications differ from e-Express, which has permanent HKID and existing-account restrictions.', ['香港永久居民身份证或认可旅行证件', '已有香港身份证（如适用）', '未成年申请人的监护人资料（如适用）'], ['Permanent HKID or accepted travel document', 'Existing HKID where applicable', 'Guardian documents for minors where applicable'], '非符合 e-Express 条件的申请人应先向网点确认；线上账户按指定方式完成启用。', 'Applicants outside e-Express criteria should contact a branch; activate online accounts through the specified method.', 'https://dahsing.com/html/tc/deposit/deposit_account_document_list.html'),
    ocbc: profile('华侨银行（香港）个人清单列有内地身份证与有效旅行证件，并按客户背景开展尽职调查。', 'OCBC Hong Kong lists Mainland ID with a valid travel document and performs customer due diligence.', ['认可身份证明及旅行证件', '个人背景及财务活动资料', '投资账户住址证明（如适用）'], ['Accepted identification and travel documents', 'Personal background and financial activity details', 'Investment-account address proof where applicable'], '使用香港个人账户清单确认文件并向银行申请。', 'Confirm documentation using the Hong Kong personal-account checklist.', 'https://www.ocbc.com.hk/webpages/en-us/doc/download_form/pdf/Checklist_PersonalAccount.pdf'),
    citi: profile('花旗香港个人开户流程接受香港身份证或有效旅行证件；未成年账户有年龄和监护人安排，不能统一套用成年渠道条件。', 'Citibank Hong Kong accepts HKID or a valid travel document. Minor accounts have age and guardian arrangements distinct from adult channels.', ['香港身份证或有效旅行证件', '投资服务近期住址证明（如适用）', '未成年客户监护人资料（如适用）'], ['HKID or valid travel document', 'Recent address proof for investment services where applicable', 'Guardian details for minors where applicable'], '依据个人开户流程确认产品与申请安排。', 'Confirm product eligibility through the personal account-opening process.', 'https://www.citibank.com.hk/english/personal-banking/pdf/useful-documents/personal-account-opening-process.pdf'),
    sc: profile('渣打香港手机开户 FAQ 所述渠道要求适用香港身份证，并限制美国人士；居住内地不等于可仅凭内地身份证使用此渠道。', 'Standard Chartered Hong Kong’s mobile FAQ requires an eligible HKID and restricts U.S. persons. Mainland residence alone does not establish Mainland-ID eligibility.', ['适用香港身份证', '个人、居住地及税务资料', '其他身份的申请须向网点确认文件'], ['Eligible HKID', 'Personal, residence and tax details', 'Confirm branch documents for other identity types'], '符合手机渠道资格者使用银行 App；其他身份先咨询网点。', 'Use the app if eligible; contact a branch for other identity types.', 'https://www.sc.com/hk/help/deposits/mobile-account-opening/'),
    'shanghai-commercial': profile('上海商业银行个人及联名账户文件清单要求所有持有人及签署人按银行安排出席，非永久居民需认可旅行证件。', 'Shanghai Commercial Bank’s checklist requires account holders and signatories to attend as arranged, with accepted travel documents for non-permanent residents.', ['认可身份证明或旅行证件', '联名持有人及签署人的身份资料', '银行要求的其他补充证明'], ['Accepted identity or travel document', 'Identification of joint holders and signatories', 'Additional evidence requested by the bank'], '联名账户须一并确认所有相关人士的到场安排。', 'Confirm attendance arrangements for every relevant joint-account party.', 'https://www.shacombank.com.hk/eng/personal/deposits/pdf/req_personal_joint.pdf')
  },
  sg: {
    ocbc: profile('华侨新加坡外国护照数字开户与赴新工作、学习或生活计划相关，不是无条件海外开户渠道。', 'OCBC Singapore foreign-passport digital onboarding is linked to plans to work, study or live in Singapore.', ['支持的电子护照及适用身份证明', '赴新工作、学习或生活的证明', '地址及申请所需的补充证明'], ['Supported biometric passport and applicable ID', 'Evidence of work, study or relocation plans', 'Address and additional application evidence'], '使用支持 NFC 的手机按官方数字开户 FAQ 申请。', 'Follow the digital onboarding FAQ using an NFC-enabled phone.', 'https://www.ocbc.com/iwov-resources/sg/ocbc/personal/pdf/digitalbanking/faq-for-sg-bank-account.pdf'),
    dbs: profile('星展新加坡外国申请人文件包括护照、适用新加坡准证或批准文件，以及地址和税务资料。', 'DBS Singapore requests a passport, applicable Singapore pass or approval documentation, address and tax information for foreign applicants.', ['有效护照', '适用工作、学生、家属准证或批准文件', '近期住址及各税务居民地证明'], ['Valid passport', 'Applicable work, student, dependant pass or approval', 'Recent address and tax-residency evidence'], '按外国申请人清单提交资料，避免使用不被接受的地址证明。', 'Follow the foreign-applicant checklist and accepted address-proof rules.', 'https://www.dbs.com.sg/personal/support/bank-account-opening-documents-required.html'),
    hsbc: profile('汇丰新加坡个人开户说明对外国居民列有护照、适用准证及住址证明要求。', 'HSBC Singapore’s personal opening notes list passport, applicable pass and address-proof requirements for foreign residents.', ['有效护照', '适用新加坡准证或批准函', '近期住址证明及税务居民资料'], ['Valid passport', 'Applicable Singapore pass or approval letter', 'Recent address proof and tax-residency details'], '依个人开户表格说明向银行确认办理渠道。', 'Confirm the channel using the personal account-opening notes.', 'https://www.hsbc.com.sg/content/dam/hsbc/sg/documents/account-opening-form-notes.pdf'),
    maybank: profile('Maybank 新加坡 iSAVvy 储蓄账户有产品年龄要求；外国申请人网点开户须提供护照及适用准证，线上资格另行判断。', 'Maybank Singapore iSAVvy has product-specific age criteria. Foreign branch applicants need a passport and eligible pass; online eligibility is separate.', ['有效护照', '适用就业、S 或学生准证', '与申请人姓名一致的住址证明'], ['Valid passport', 'Applicable employment, S or student pass', 'Address proof matching the applicant’s name'], '按 iSAVvy 产品页面确认网点或线上资格及初始存款。', 'Confirm branch/online eligibility and opening deposit on the iSAVvy product page.', 'https://www.maybank2u.com.sg/en/personal/accounts/savings/iSAVvy-Savings-Account.page'),
    sc: profile('渣打新加坡对在新工作外国人士列有护照、就业及住址文件要求，开户须结合所选产品资格。', 'Standard Chartered Singapore lists passport, employment and address evidence for foreigners working in Singapore, alongside product eligibility.', ['有效护照', '适用就业准证', '地址账单或银行接受的雇主/政府证明'], ['Valid passport', 'Applicable employment pass', 'Address bill or accepted employer/government evidence'], '先核对外国人士文件及产品条件，再提交个人申请。', 'Check foreign-applicant documents and product criteria before applying.', 'https://www.sc.com/sg/help/general-information/'),
    uob: profile('大华银行提供外国人士在新加坡开户说明；身份、在新居留及地址资料须按个人情况核对。', 'UOB provides guidance for foreigners opening Singapore accounts, with identity, local status and address checks.', ['有效护照', '适用新加坡居留或工作证明', '银行接受的住址证明'], ['Valid passport', 'Applicable Singapore residence or employment evidence', 'Accepted address proof'], '参考外国人士开户指南，并确认目标网点及所选账户要求。', 'Use the foreigner guide and confirm branch and account requirements.', 'https://www.uob.com.sg/personal/highlights/life-moments/foreigner-open-bank-account-in-singapore.page'),
    citi: profile('花旗新加坡 Citi Plus / Interest Booster 外国申请人渠道要求成年、有效护照及银行列明的新加坡准证。', 'Citibank Singapore’s Citi Plus / Interest Booster foreign channel requires adulthood, a valid passport and a listed Singapore pass.', ['剩余有效期符合要求的护照', '银行接受的工作、家属、长期居留或学生准证', '个人开户申请所需补充资料'], ['Passport meeting remaining-validity requirements', 'Accepted work, dependant, long-term or student pass', 'Additional personal application information'], '按 Citi Plus FAQ 确认资格后使用相应申请入口。', 'Confirm eligibility in the Citi Plus FAQ before applying.', 'https://www1.citibank.com.sg/wealth-management/citi-plus/faqs'),
    boc: profile('中国银行新加坡个人储蓄账户接受符合条件的外国准证持有人，外国申请人网点材料与本地线上渠道不同。', 'Bank of China Singapore accepts eligible foreign pass holders for personal savings accounts; foreign branch documentation differs from local online onboarding.', ['有效护照', '适用工作、学生、长期居留或家属准证', '近期住址证明'], ['Valid passport', 'Applicable work, student, long-term or dependant pass', 'Recent address proof'], '外国申请人先按产品页面核对准证有效期及网点文件。', 'Foreign applicants should check pass validity and branch documentation on the product page.', 'https://www.bankofchina.com/sg/pbservice/pb1/201001/t20100120_955816.html'),
    bos: profile('新加坡银行是华侨集团旗下私人银行，主要服务高净值个人及家族，应以私人银行关系评估为入口。', 'Bank of Singapore is OCBC’s private bank for high-net-worth individuals and families, with relationship-based assessment.', ['客户身份及税务居民资料由私人银行确认', '财富与资金来源资料按尽职调查要求提供', '具体资产门槛及文件清单须由银行确认'], ['Identity and tax-residency details confirmed by the private bank', 'Wealth and funding evidence under due diligence', 'Confirm asset thresholds and documents with the bank'], '联系私人银行评估客户关系；不作为普通零售储蓄账户申请。', 'Contact the private bank for relationship assessment, rather than retail savings onboarding.', 'https://www.ocbc.com/group/media/group-business-private-banking.html', 'private')
  },
  mo: {
    wl: profile('立桥银行官方个人文件清单分别列有澳门/香港、内地及其他地区居民要求，内地申请还可能需要代理银行介绍信。', 'Well Link Bank publishes separate personal requirements for Macao/Hong Kong, Mainland and other residents, with a correspondent introduction where required.', ['有效护照，或身份证及旅行证件', '三个月内的居住地址证明', '个人申请、签名卡、W8/W9 及税务居民自证'], ['Valid passport, or ID and travel document', 'Residential address proof within three months', 'Personal form, signature card, W8/W9 and tax self-certification'], '依清单核对申请及见证安排；未出席人士的签名和副本认证有特别要求。', 'Check application and witnessing arrangements; absent applicants have specific signature and copy-certification requirements.', 'https://www.wlbank.com.mo/webfile/upload/2025/05-12/09-25-360980-877442630.pdf'),
    hsbc: profile('汇丰澳门提供个人独立户口申请表，非澳门永久居民须补充旅行或国籍证明，并申报个人、职业及税务信息。', 'HSBC Macao publishes a personal sole-account form. Non-permanent residents need travel or nationality evidence and personal, employment and tax disclosures.', ['有效身份证明文件', '非永久居民的旅行或国籍证明', '住址、职业及适用税务声明资料'], ['Valid identity document', 'Travel or nationality evidence for non-permanent residents', 'Address, employment and applicable tax declarations'], '向澳门分行确认个人申请安排，按独立户口表格准备材料。', 'Confirm arrangements with the Macao branch using the personal sole-account form.', 'https://www.hsbc.com.mo/content/dam/hsbc/hbap_mo/documents/accounts/personal-sole-account-opening-form.pdf'),
    ocbc: profile('华侨澳门个人/联名清单对非澳门居民列明外地雇员身份识别证要求，不能据此宣传普通访客均可开户。', 'OCBC Macao’s personal/joint checklist requires a non-resident worker card for non-Macao residents; it does not establish general visitor eligibility.', ['有效身份证明及三个月内住址证明', '非澳门居民的外地雇员证、旅行及入境资料（适用时）', 'FATCA 声明及税务居民自我证明'], ['Valid ID and address proof within three months', 'Non-resident worker card, travel and entry documents where applicable', 'FATCA declaration and tax self-certification'], '确认非居民资格后预约个人开户，不沿用香港华侨的要求。', 'Confirm non-resident eligibility before booking; Hong Kong OCBC rules do not apply.', 'https://www.ocbc.com.mo/file/Forms_Enquiries/doc_required_for_ac_opening_tc.pdf')
  },
  us: {
    cbi: profile('富港银行个人页面列有多币种汇款、银行卡及 App 申请流程，其主体为波多黎各 CB International Bank LLC。公开产品页未列完整非居民资格。', 'CBiBank’s personal page describes currency transfers, cards and app onboarding. Its entity is CB International Bank LLC in Puerto Rico; full non-resident eligibility is not listed there.', ['通过官方 App 完成实名资料提交', '银行要求的身份及补充资料须在申请时确认', '费用使用个人产品对应的官方定价表'], ['Submit real-name information through the official app', 'Confirm identity and supporting evidence during application', 'Use the official pricing for the selected personal product'], 'App 注册、实名信息提交、视频面谈及银行审核；不承诺固定获批时限。', 'App registration, real-name submission, video interview and bank review; no guaranteed approval time.', 'https://m.cbibank.com/perbank'),
    ew: profile('华美银行 Global Student Family Bridge 为符合条件的学生与家属提供账户关联安排，申请可用性受所在地和计划资格限制。', 'East West Bank’s Global Student Family Bridge links eligible student and family accounts, subject to location and programme eligibility.', ['学生账户及计划资格资料', '家庭成员关系及对应账户申请信息', '身份证明及其他资料以具体产品申请为准'], ['Student-account and programme eligibility information', 'Family relationship and relevant account application information', 'Identity and other evidence under the selected product'], '先核对学生/家属计划资格，再按银行 App 与产品流程申请。', 'Check student/family programme eligibility before using the bank’s app and product workflow.', 'https://www.eastwestbank.com/en/personal-banking/global-student-family-bridge-program'),
    cathay: profile('国泰银行数字个人开户入口仅列明指定美国州居民可申请，不能当作海外非居民线上开户依据。', 'Cathay Bank’s digital personal opening page accepts residents of listed U.S. states; this is not evidence of overseas non-resident online eligibility.', ['居住州符合数字开户入口范围', '所选产品申请要求的个人身份资料', '其他身份申请先向网点确认'], ['Residence in a state accepted by digital onboarding', 'Personal identification required by the selected product', 'Contact a branch for other applicant profiles'], '选择居住州进入官方数字申请；不在范围内须先咨询银行。', 'Select an eligible state for digital onboarding; contact the bank if outside that scope.', 'https://www.cathaybank.com/zh-hans/open-an-account'),
    boa: profile('美国银行的国际专业人士指南接受非美国公民。非居民需海外实际居住地址及美国邮寄地址；居民身份申请需美国实际居住地址。', 'Bank of America’s international professional guide accepts non-U.S. citizens. Non-resident aliens need a foreign physical address and U.S. mailing address; resident aliens need a U.S. physical address.', ['两份有效身份证明，包括认可的主要及辅助证件', '适用的海外/美国地址资料', '适用税号；不将 SSN 写成所有申请人的必需条件'], ['Two unexpired forms of accepted primary and secondary ID', 'Applicable foreign/U.S. address information', 'Applicable tax ID; SSN is not required for every applicant'], '预约美国金融中心并携带资料到场办理。', 'Book a U.S. financial-center appointment and bring the required documents.', 'https://info.bankofamerica.com/en/international/professional-bank-account'),
    hsbc: profile('汇丰美国个人申请须成年并处于银行支持的申请地区；不同账户及国际渠道有独立资格要求。', 'HSBC USA personal applicants must be adults in a supported application location; accounts and international channels have separate eligibility criteria.', ['符合有效期要求的护照等身份证明', '永久地址证明，如银行结单或公共事业账单', '职业、收入、税务信息及在学证明（适用时）'], ['Identity evidence such as a passport meeting validity rules', 'Permanent-address proof such as a bank statement or utility bill', 'Employment, income, tax details and enrolment proof where applicable'], '核对支持地区及所选账户资格后使用官方个人申请渠道。', 'Check supported locations and account eligibility before using official personal onboarding.', 'https://www.us.hsbc.com/checking-accounts/what-do-you-need-to-open-a-checking-account/'),
    arival: profile('Arival 当前官方产品以企业账户、企业跨境支付及团队权限为主，尚无足够依据将此入口作为普通个人开户服务。', 'Arival’s current official product focuses on business accounts, corporate payments and team controls. It does not establish ordinary personal onboarding.', ['普通个人账户资格未确认', '不使用公司注册文件作为个人开户清单', '可返回个人银行列表选择其他银行'], ['Ordinary personal-account eligibility is unconfirmed', 'Corporate registration documents are not a personal checklist', 'Return to the personal bank list to select another bank'], '此入口保留适用范围说明，不提供虚构的个人申请流程。', 'This legacy entry explains suitability without inventing a personal application process.', 'https://arival.com/product', 'unavailable')
  }
}

const pending = (zh, en, source) => profile(zh, en,
  ['先由银行确认申请人身份及居民资格', '个人产品文件清单尚未完整核验', '不套用其他银行或公司账户的材料要求'],
  ['Confirm identity and residency eligibility with the bank', 'A complete personal-product checklist has not been verified', 'Do not substitute another bank’s or corporate documents'],
  '先通过官方个人服务入口确认产品、资格、文件及办理渠道，再安排申请。',
  'Confirm product, eligibility, documents and channel through official personal services before applying.', source, 'pending')
Object.assign(personalBankProfiles.hk, {
  chonghing: profile('创兴银行个人开户清单区分永久居民、香港居民及非香港居民；非香港居民须提供有效护照或旅行证件。', 'Chong Hing distinguishes permanent, Hong Kong and non-Hong Kong residents; non-residents require a valid passport or travel document.', ['适用身份证明及旅行证件', '居住地址（不接受邮政信箱）及职业雇佣资料', '开户目的、预期活动、财富及资金来源'], ['Applicable identity and travel documents', 'Residential address (no PO box) and employment details', 'Purpose, expected activity, wealth and funding sources'], '按官方个人开户清单核对资料，并向银行确认办理安排。', 'Check the official personal checklist and confirm application arrangements with the bank.', 'https://www.chbank.com/en/personal/banking-services/useful-information/documents-required/index.shtml'),
  bea: profile('东亚银行个人及联名账户清单要求持有人和授权签署人的身份证明；无香港身份证者须提供有效护照或旅行证件。', 'BEA’s personal/joint checklist requires identification for holders and authorised signatories; applicants without HKID need a valid passport or travel document.', ['有效身份证明，或适用护照/旅行证件', '银行要求的原件或合资格人士认证副本', '综合/投资账户等适用服务的住址证明（不接受邮政信箱）'], ['Valid ID or applicable passport/travel document', 'Originals or copies certified by an eligible certifier', 'Address proof for applicable integrated/investment services; no PO box'], '按银行现行个人文件清单提交，补充审核资料后由银行决定是否受理；手机渠道资格另行确认。', 'Follow the bank’s current personal checklist and additional review requests; confirm mobile eligibility separately.', 'https://www.hkbea.com/pdf/en/Personal%20Account(ENG)_082020.pdf'),
  icbc: profile('工银亚洲全新客户网点开户支持成年内地身份证持有人预填手机申请，但必须在香港预约分行完成核验及启用。', 'ICBC Asia’s new-customer branch service lets adult Mainland ID holders submit mobile applications, followed by verification and activation at a booked Hong Kong branch.', ['有效内地身份证及港澳通行证或中国护照，须满足剩余有效期要求', '可接收验证码的内地手机号码及有效电邮', '地址、就业、开户目的、资金来源及税务资料'], ['Valid Mainland ID and Exit/Entry Permit or PRC passport meeting validity rules', 'Mainland mobile number receiving verification codes and valid email', 'Address, employment, purpose, funding and tax information'], '手机预填申请、预约网点；预审批后携带原件赴香港分行核验启用。', 'Submit mobile details and book a branch; after pre-approval, bring originals to Hong Kong for verification and activation.', 'https://www.icbcasia.com/hk/sc/promotion/mobile-banking-account-opening-service.html')
})
Object.assign(personalBankProfiles.mo, {
  'icbc-asia': pending('原“澳门工银亚洲”入口的银行主体存在歧义。工银亚洲与工银澳门须分别确认，此处暂不发布确定开户条件。', 'The legacy “ICBC Asia (Macao)” entity is ambiguous. ICBC Asia and ICBC Macao must be distinguished before publishing opening criteria.', 'https://www.icbc.com.mo/'),
  boc: pending('澳门中国银行个人服务的适用主体、非居民资格及办理渠道须向当地银行确认，不沿用公司开户介绍。', 'Confirm the entity, non-resident eligibility and channel for Bank of China personal services in Macao; corporate descriptions are not reused.', 'https://www.bankofchina.com/mo/bocinfo/cs8/'),
  lusobank: pending('澳门国际银行官网列有个人储蓄及往来存款业务，非居民资格与完整文件清单仍须向银行确认。', 'Luso International Banking lists personal savings and current deposits; non-resident eligibility and the full checklist need confirmation.', 'https://www.lusobank.com.mo/'),
  cgb: pending('广发澳门个人开户应以澳门当地产品及分行规则为依据，当前不将内地开户说明作为澳门申请条件。', 'CGB Macao applications require local product and branch rules; Mainland opening instructions are not used as Macao eligibility.', 'https://www.cgbchina.mo.cn/')
})
personalBankProfiles.us.axos = pending('Axos 提供个人数字银行服务，但当前资料未完整核验海外非居民的开户资格及文件要求。', 'Axos provides personal digital banking, but overseas non-resident eligibility and documentation have not been fully verified.', 'https://www.axosbank.com/personal')

export const isListedPersonalBank = (region, slug) => {
  const item = personalBankProfiles[region]?.[slug]
  return item?.status === 'personal'
}
